# Generated by Django 2.2.10 on 2020-02-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Nome do cliente')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Idade do cliente')),
                ('city', models.CharField(max_length=2, verbose_name='Cidade do cliente')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
            },
        ),
    ]
