# Generated by Django 2.2.10 on 2020-02-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Cidade do cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome do cliente'),
        ),
    ]
